added assets and features to work sections
Geoelycom/M-portfolio pull request #2
Opened 2021-06-05 00:51 UTC by Geoelycom

This section contains the work section of the portfolio, with flexbox and grid.

2021-06-05 01:48 UTC, henatan99 requested changes
Hi Elyan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] OPTIONAL: Please use simple present tense or imperative tense in your commit messages. 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 01:48 UTC, henatan99 commented on index.html
> +			</ul>
- [ ] You have misused the `ul` and `li` tags in the entire `project-works` section. `ul` is a wrapper tag for more than one `li` items. All the `work` and `big-project` class elements should have `li` tag. In this section, avoid the `ul` and `li` tags except for the one for the 'programming-languages` class element.  Kindly apply the same change for similar sections/elements. 
- [ ] Some typography and color are different from the original design in this section. Please stick to the original design. 

![Screenshot (4)](https://user-images.githubusercontent.com/64894927/120876014-22e43400-c5b7-11eb-8dda-1b18665110ac.png)  ![Screenshot (5)](https://user-images.githubusercontent.com/64894927/120876019-27105180-c5b7-11eb-87b7-ab00cadbcbac.png)

- [ ] There is also alignment problems in the projects section. Kindly fix this. 
![Screenshot (6)](https://user-images.githubusercontent.com/64894927/120876115-9ab25e80-c5b7-11eb-8180-03c9663412ff.png)

2021-06-05 01:48 UTC, henatan99 commented on index.html
> +					<h2><a href="#">See Project</a></h2>
- [ ] Here the semantic tags are ok, but you should make a styling for it so that it looks a clickable element. Also follow the original design.

2021-06-05 01:48 UTC, henatan99 commented on index.html
> +			<h2><a href="#">Get my resume</a></h2>
- [ ] Good to make this element heading and link. But it should be displayed as a clickable element. You should also stick to the original design.

2021-06-05 01:48 UTC, henatan99 commented on index.html
> +			<img src="Assets/images/SkillList.png" alt="skills-pics">
- [ ] You put the whole technology category in a single screenshot image. The shortcut didn't work. :laughing: :+1: Please work on this section with the appropriate HTML elements.

2021-06-05 01:48 UTC, henatan99 commented on index.html
> +			</p>
- [ ] There is a misalignment of the `p` tag section. Kindly refer to the attached screenshot and make the necessary changes. 

![Screenshot (7)](https://user-images.githubusercontent.com/64894927/120876321-d13ca900-c5b8-11eb-9c11-fdab527365bc.png)

2021-06-06 00:04 UTC, sinansevgi approved these changes
# Approved :heavy_check_mark: 

Hi @Geoelycom , 

Good work with making all the changes requested by the previous TSE. :+1: 
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-06 00:06 UTC, merged